WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

PADDLE_WIDTH = 10
PADDLE_HEIGHT = 60
PADDLE_SPEED = 300
PADDLE_HSPEED = 200

-- limeted on x (horizontal) for left and rights players
BAT_MAX_X = (WINDOW_WIDTH / 2) - PADDLE_WIDTH - 10
BAT_MIN_X_OPP = (WINDOW_WIDTH / 2) + 10

BALL_SIZE = 10       -- radius ball
BALL_SPEED_X = 240
BALL_SPEED_Y = 120

WIN_SCORE = 10

PADDLE_OFFSET_X = 30
SCORE_OFFSET_Y = 40

COLOR_BG = {0, 0, 0}
COLOR_FG = {1, 1, 1}

